routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('product', 'ProductController');
Route::resource('sale', 'SaleController');
Route::resource('management-sale', 'ManagementSaleController');

app/Models/Sale.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Sale extends Model
{
    protected $fillable = [
        'user_id',
        'product_id',
        'invoiced',
        'invoiced_by',
    ];

    public function user()
    {
        return $this->belongsTo(User::class,'user_id');
    }

    public function product()
    {
        return $this->belongsTo(Product::class,'product_id');
    }

    public function invoicedBy()
    {
        return $this->belongsTo(Users::class,'invoiced_by');
    }
}

app/Http/Controllers/SaleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Models\Sale;
use Illuminate\Http\Request;

class SaleController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $product = Product::all();

        return view('sale.sale',compact('product'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = $request->user();
        $user->sale()->create([
           'product_id' => $request->producto,
       ]);

       return redirect('sale')->with('message','Comprado');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/sale/detail-sale.blade.php
@extends('layouts.app')

@section('content')
<meta name="csrf-token" content="{{ csrf_token() }}">
<div class="container">
        <div class="row justify-content-center">
            <div class="card text-center">
                <div class="card-header">
                    Factura # {{$managementSale->id}}
                </div>
                <div class="card-body">
                    <h5 class="card-title">Cleinte: {{$managementSale->user->name}}</h5>
                    <p class="card-text">Producto : {{$managementSale->product->name}}</p>
                    <p class="card-text">Precio : {{ $managementSale->product->price }} </p>
                    <p class="card-text">Impuesto : {{ $managementSale->product->tax }}</p>
                    <p class="card-text">Total : {{ ($managementSale->product->price * $managementSale->product->tax)/100 +  $managementSale->product->price }}</p>
                </div>
                <div class="card-footer text-muted">
                    {{  date('d/m/Y') }}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/sale/management-sale.blade.php
@extends('layouts.app')

@section('content')
<meta name="csrf-token" content="{{ csrf_token() }}">
<div class="container">
@if (session('message'))
    <div class="alert alert-success">
        {{ session('message') }}
    </div>
@endif
    <div class="row justify-content-center">
        <h5>Facturas Pendientes</h5>
    <table class="table">
        <thead>
            <tr>
            <th>#</th>
            <th>Cliente</th>
            <th>Producto</th>
            <th>Precio</th> 
            <th>--</th>
            </tr>
        </thead>
        <tbody>
            @foreach($toInvoice as $invoice)
            <tr>
                <td>{{ $invoice->id }}</td>
                <td>{{ $invoice->user->name }}</td>
                <td>{{ $invoice->product->name }}</td>
                <td>{{ $invoice->product->price }}</td>
                <td>
                    <form action="{{route('management-sale.store')}}" method="post">
                    @csrf
                    <input type="hidden" value="{{$invoice->id}}" name="invoice">
                    <button class="btn btn-success btn-sm btn-round">Facturar..</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    <br>
    <h5>Facturas Emitidas</h5>
    <table class="table">
        <thead>
            <tr>
            <th>#</th>
            <th>Cliente</th>
            <th>Producto</th>
            <th>Precio</th> 
            <th>--</th>
            </tr>
        </thead>
        <tbody>
            @foreach($invoiced as $invoice)
            <tr>
                <td>{{ $invoice->id }}</td>
                <td>{{ $invoice->user->name }}</td>
                <td>{{ $invoice->product->name }}</td>
                <td>{{ $invoice->product->price }}</td>
                <td>
                    <form action="{{route('management-sale.show',$invoice->id)}}" method="GET">
                    @csrf
                    <button class="btn btn-success btn-sm btn-round">Ver Detalle..</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    </div>
</div>
@endsection

resources/views/sale/sale.blade.php
@extends('layouts.app')

@section('content')
<meta name="csrf-token" content="{{ csrf_token() }}">
<div class="container">
@if (session('message'))
    <div class="alert alert-success">
        {{ session('message') }}
    </div>
@endif
    <div class="row justify-content-center">
    <table class="table">
        <thead>
            <tr>
            <th>#</th>
            <th>Nombre</th>
            <th>Precio</th>
            <th>Impuesto</th>
            <th>--</th>
            </tr>
        </thead>
        <tbody>
            @foreach($product as $products)
            <tr>
                <td>{{ $products->id }}</td>
                <td>{{ $products->name }}</td>
                <td>{{ $products->price }}</td>
                <td>{{ $products->tax }}</td>
                <td>
                    <form action="{{route('sale.store')}}" method="post">
                    @csrf
                    <input type="hidden" value="{{$products->id}}" name="producto">
                    <button class="btn btn-success btn-sm btn-round">Comprar</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    </div>
</div>
@endsection