routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('product', 'ProductController');
Route::resource('sale', 'SaleController');
Route::resource('management-sale', 'ManagementSaleController');

app/Models/Product.php
<?php

namespace App\Models;


use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
            'name',
            'price',
            'tax',
    ];
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductStoreRequest;
use App\Http\Requests\ProductUpdateRequest;
use App\Models\product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $product = product::all();

      return view('product.product',compact('product'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('product.create-product');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductStoreRequest $request)
    {
        product::create($request->validated());
        
        return redirect('product');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('product.create-product',compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProductUpdateRequest $request, Product $product)
    {
        $product->update($request->validated());
        
        return back()->with('message', 'Actualizado con existo!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();
        return redirect('product')->with('message', 'Eliminado con existo!');
    }
}

resources/views/product/create-product.blade.php
@extends('layouts.app')

@section('content')
<meta name="csrf-token" content="{{ csrf_token() }}">
<div class="container">
@if (session('message'))
    <div class="alert alert-success">
        {{ session('message') }}
    </div>
@endif
    <div class="row justify-content-center">
        <h5>Nuevo Producto</h5>
        
        @if(isset($product))
        <form method="POST" action="{{route('product.update', $product->id)}}">
        @csrf 
        @method('PUT')
        @else
        <form method="POST" action="{{route('product.store')}}">    
        @csrf
        @method('POST')
        @endif

        <div class="form-group">
            <label for="producto">Nombre del Producto</label>
            <input type="text" class="form-control" id="nombre"  name="name" placeholder="Ingrese el nombre."
            @isset($product) value="{{$product->name}}" @endisset
            >
        </div>
        <div class="form-group">
            <label for="precio">Precio</label>
            <input type="text" class="form-control" id="precio" placeholder="Precio" name="price"
            @isset($product) value="{{$product->price}}" @endisset
            >
        </div>
        <div class="form-group">
            <label for="impuesto">Impuesto</label>
            <input type="text" class="form-control" id="impuesto" placeholder="Impuesto" name="tax"
            @isset($product) value="{{$product->tax}}" @endisset
            >
        </div>
        <button type="submit" class="btn btn-primary btn-large">Submit</button>
    </form>
    </div>
</div>
@endsection

resources/views/product/product.blade.php
@extends('layouts.app')

@section('content')
<meta name="csrf-token" content="{{ csrf_token() }}">
<div class="container">
@if (session('message'))
    <div class="alert alert-success">
        {{ session('message') }}
    </div>
@endif
    <div class="row justify-content-center">
        <a class="btn btn-primary btn-large" href="{{route('product.create')}}">Agregar</a>
        <br>
    <table class="table">
        <thead>
            <tr>
            <th>#</th>
            <th>Nombre</th>
            <th>Precio</th>
            <th>Impuesto</th>
            <th>--</th>
            </tr>
        </thead>
        <tbody>
            @foreach($product as $products)
            <tr>
                <td>{{ $products->id }}</td>
                <td>{{ $products->name }}</td>
                <td>{{ $products->price }}</td>
                <td>{{ $products->tax }}</td>
                <td>
                    <form action="{{route('product.edit', $products->id)}}">
                    @csrf
 
                    <button class="btn btn-warning btn-sm btn-round">Editar</button>
                    </form>
                    
                    <form action="{{route('product.destroy', $products->id)}}" method="POST">
                    @csrf
                    @method('DELETE')
                        <button class="btn btn-danger btn-sm btn-round">Eliminar</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    </div>
</div>
@endsection